spring:
  datasource:
    url: jdbc:h2:mem:ppdb
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080
